### ISSUE TITLE
click'ni testlash uchun click.exe'ga oxshash dasturni linux'ga ham chiqarganmi? 

### ISSUE THREAD

**Issue by blvckeasy** [begyy/ClickUz#1]

**Comment by blvckeasy** [comment]
https://docs.click.uz/en/click-api-testing/

**Comment by begyy** [comment]
> https://docs.click.uz/en/click-api-testing/
Salom yoq linuxga chiqarmagan faqat windows uchun postman orqali lekn tekshirb osez boladi
